pub mod commands;
pub mod graph;
pub mod models;
pub use models::*;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_store::Builder::default().build())
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .manage(commands::watcher::WatcherState::default())
        .manage(commands::history::HistoryCache::default())
        .manage(commands::repo::CloneState::default())
        .manage(commands::branches::AheadBehindCache::default())
        .invoke_handler(tauri::generate_handler![
            commands::repo::open_repo,
            commands::repo::clone_repo,
            commands::repo::cancel_clone,
            commands::repo::get_recent_repos,
            commands::repo::add_recent_repo,
            commands::commits::git_log,
            commands::changes::get_working_changes,
            commands::branches::list_branches,
            commands::branches::checkout_branch,
            commands::branches::fast_forward,
            commands::branches::list_tags,
            commands::diff::get_diff,
            commands::diff::get_commit_diff,
            commands::graph::get_graph_data,
            commands::hunks::stage_hunks,
            commands::hunks::unstage_hunks,
            commands::hunks::apply_patch,
            commands::staging::stage_files,
            commands::staging::unstage_files,
            commands::staging::create_commit,
            commands::staging::get_head_commit_message,
            commands::staging::discard_changes,
            commands::staging::ignore_path,
            commands::staging::set_assume_unchanged,
            commands::remote::fetch_remote,
            commands::remote::pull,
            commands::remote::push,
            commands::remote::list_remotes,
            commands::remote::add_remote,
            commands::remote::remove_remote,
            commands::remote::rename_remote,
            commands::remote::set_remote_url,
            commands::merge::merge_branch,
            commands::merge::get_conflicts,
            commands::merge::get_merge_content,
            commands::merge::resolve_conflict,
            commands::merge::resolve_conflict_take,
            commands::merge::resolve_conflict_delete,
            commands::merge::abort_merge,
            commands::stash::stash_save,
            commands::stash::stash_list,
            commands::stash::stash_apply,
            commands::stash::stash_drop,
            commands::stash::stash_show,
            commands::stash::stash_branch,
            commands::advanced::cherry_pick,
            commands::advanced::revert_commit,
            commands::advanced::rebase_branch,
            commands::advanced::reset_to_commit,
            commands::advanced::get_rebase_todo,
            commands::advanced::apply_rebase,
            commands::advanced::blame_file,
            commands::advanced::file_history,
            commands::watcher::watch_repo,
            commands::watcher::unwatch_repo,
            commands::search::search_commits,
            commands::repo_state::get_repo_state,
            commands::sequencer::rebase_continue,
            commands::sequencer::rebase_skip,
            commands::sequencer::rebase_abort,
            commands::sequencer::cherry_pick_continue,
            commands::sequencer::cherry_pick_skip,
            commands::sequencer::cherry_pick_abort,
            commands::sequencer::revert_continue,
            commands::sequencer::revert_skip,
            commands::sequencer::revert_abort,
            commands::sequencer::merge_continue,
            commands::branch_ops::create_branch,
            commands::branch_ops::delete_branch,
            commands::branch_ops::rename_branch,
            commands::branch_ops::set_upstream,
            commands::branch_ops::delete_remote_branch,
            commands::branch_ops::checkout_commit,
            commands::branch_ops::compare_refs,
            commands::tags::create_tag,
            commands::tags::delete_tag,
            commands::tags::push_tag,
            commands::tags::delete_remote_tag,
            commands::commit_details::get_commit_details,
            commands::commit_details::get_commit_file_diff,
            commands::commit_details::get_file_at_revision,
            commands::commit_details::get_file_base64,
            commands::history::get_history,
            commands::config::get_repo_config,
            commands::config::set_config_value,
            commands::reflog::get_reflog,
            commands::system::open_in_file_manager,
            commands::system::open_in_terminal,
            commands::system::open_in_editor,
            commands::system::open_url,
            commands::system::init_repo,
            commands::system::remove_recent_repo,
            commands::system::get_git_version,
            commands::ai::generate_commit_message,
            commands::ai::test_ai_provider,
            commands::ai::preview_ai_prompt,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
